"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const province_route_1 = require("./province.route");
const category_route_1 = require("./category.route");
const event_route_1 = require("./event.route");
const auth_route_1 = __importDefault(require("./auth.route"));
const user_route_1 = __importDefault(require("./user.route"));
const organizer_route_1 = __importDefault(require("./organizer.route"));
const search_route_1 = require("./search.route");
const review_route_1 = require("./review.route");
const transaction_route_1 = __importDefault(require("./transaction.route"));
const dashboard_route_1 = __importDefault(require("./dashboard.route"));
const ping_route_1 = __importDefault(require("./ping.route"));
const voucher_route_1 = require("./voucher.route");
const apiRouter = (0, express_1.Router)();
apiRouter.use('/', (0, province_route_1.provinceRouter)());
apiRouter.use('/', (0, category_route_1.categoryRouter)());
apiRouter.use('/', (0, event_route_1.eventRouter)());
apiRouter.use('/', (0, search_route_1.searchRouter)());
apiRouter.use('/', (0, review_route_1.reviewRouter)());
apiRouter.use('/', (0, voucher_route_1.voucherRouter)());
apiRouter.use('/auth', auth_route_1.default);
apiRouter.use('/users', user_route_1.default);
apiRouter.use('/organizers', organizer_route_1.default);
apiRouter.use('/transactions', transaction_route_1.default);
apiRouter.use('/dashboard', dashboard_route_1.default);
apiRouter.use('/ping', ping_route_1.default);
exports.default = apiRouter;
